language: python
cache: pip
matrix:
  include:
    - arch: arm64
      python: 2.7
    - arch: amd64
      python: 2.7
    - arch: arm64
      python: 3.8
    - arch: amd64
      python: 3.8
    - dist: bionic
      os: linux
      arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - arch: arm64
      python: 3.6
    - arch: amd64
      python: 3.6
    - arch: arm64
      python: 3.5
    - arch: amd64
      python: 3.5
    - arch: amd64
      python: pypy
install:
  - "pip install mock asn1crypto cryptography idna keyring keyrings.alt pycrypto pyxdg SecretStorage"
  - python -m pip freeze
script: "python -m unittest discover -v -p *_test.py"
